In [16]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.io as pio
pio.renderers.default = "notebook"  #makes it render on jupyter notebook

In [2]:
#getting the latitude and longitued of cities in kenya from jinyi-solar.com
nasa_wind_dataset_kenya = pd.read_excel("/home/raduma/csa2025/Renewable-Energy-Potential-Analyzer/data/nasa_dataset_50M_10M.xlsx")
kenya_coordinate_data = pd.read_excel("/home/raduma/csa2025/Renewable-Energy-Potential-Analyzer/data/kenya_coordinate_data.xlsx")
nasa_wind_dataset_kenya

,Town,Year,Month,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa
0,Nairobi,2018,1,21.44,5.33,83.57
1,Nairobi,2018,2,21.61,7.41,83.57
2,Nairobi,2018,3,19.27,4.73,83.61
3,Nairobi,2018,4,18.72,4.97,83.63
4,Nairobi,2018,5,17.83,4.59,83.75
...,...,...,...,...,...,...
5455,Tsavo,2024,9,25.04,6.76,96.64
5456,Tsavo,2024,10,26.54,5.73,96.50
5457,Tsavo,2024,11,26.46,4.05,96.35
5458,Tsavo,2024,12,25.76,3.76,96.39
5459,Tsavo,2024,13,25.33,5.31,96.50

In [3]:
nasa_wind_dataset_kenya.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5460 entries, 0 to 5459
Data columns (total 6 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Town                  5460 non-null   object
 1   Year                  5460 non-null   int64
 2   Month                 5460 non-null   int64
 3   Avg_Temperature_C     5460 non-null   float64
 4   Avg_Wind_Speed_m/s    5460 non-null   float64
 5   Surface_Pressure_kPa  5460 non-null   float64
dtypes: float64(3), int64(2), object(1)
memory usage: 256.1+ KB

In [4]:
#!pip install plotly

In [5]:
#deleting all the columns where month ==13
df_refined= nasa_wind_dataset_kenya.drop(
    nasa_wind_dataset_kenya[nasa_wind_dataset_kenya['Month'] == 13].index
)
df_refined

,Town,Year,Month,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa
0,Nairobi,2018,1,21.44,5.33,83.57
1,Nairobi,2018,2,21.61,7.41,83.57
2,Nairobi,2018,3,19.27,4.73,83.61
3,Nairobi,2018,4,18.72,4.97,83.63
4,Nairobi,2018,5,17.83,4.59,83.75
...,...,...,...,...,...,...
5454,Tsavo,2024,8,23.93,7.16,96.72
5455,Tsavo,2024,9,25.04,6.76,96.64
5456,Tsavo,2024,10,26.54,5.73,96.50
5457,Tsavo,2024,11,26.46,4.05,96.35
5458,Tsavo,2024,12,25.76,3.76,96.39

In [6]:
#creating Air Density from the available data
R = 287.05
df_refined["Air_Density"] = (df_refined["Surface_Pressure_kPa"]* 1000)/((df_refined["Avg_Temperature_C"]+273.15) * R)
df_refined

,Town,Year,Month,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa,Air_Density
0,Nairobi,2018,1,21.44,5.33,83.57,0.988268
1,Nairobi,2018,2,21.61,7.41,83.57,0.987698
2,Nairobi,2018,3,19.27,4.73,83.61,0.996079
3,Nairobi,2018,4,18.72,4.97,83.63,0.998194
4,Nairobi,2018,5,17.83,4.59,83.75,1.002684
...,...,...,...,...,...,...,...
5454,Tsavo,2024,8,23.93,7.16,96.72,1.134189
5455,Tsavo,2024,9,25.04,6.76,96.64,1.129032
5456,Tsavo,2024,10,26.54,5.73,96.50,1.121754
5457,Tsavo,2024,11,26.46,4.05,96.35,1.120309
5458,Tsavo,2024,12,25.76,3.76,96.39,1.123399

In [7]:
#creating column for wind power density using the formulae 
df_refined["Wind_Power_Density"] = 0.5 *(df_refined["Air_Density"]) * (df_refined["Avg_Wind_Speed_m/s"]**3)
df_refined

,Town,Year,Month,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa,Air_Density,Wind_Power_Density
0,Nairobi,2018,1,21.44,5.33,83.57,0.988268,74.821512
1,Nairobi,2018,2,21.61,7.41,83.57,0.987698,200.931919
2,Nairobi,2018,3,19.27,4.73,83.61,0.996079,52.704418
3,Nairobi,2018,4,18.72,4.97,83.63,0.998194,61.270900
4,Nairobi,2018,5,17.83,4.59,83.75,1.002684,48.481069
...,...,...,...,...,...,...,...,...
5454,Tsavo,2024,8,23.93,7.16,96.72,1.134189,208.158616
5455,Tsavo,2024,9,25.04,6.76,96.64,1.129032,174.387916
5456,Tsavo,2024,10,26.54,5.73,96.50,1.121754,105.519173
5457,Tsavo,2024,11,26.46,4.05,96.35,1.120309,37.211137
5458,Tsavo,2024,12,25.76,3.76,96.39,1.123399,29.858468

In [8]:
df_refined["Wind_Power_Density"].max()

np.float64(759.7124384805455)

In [9]:
#creating an excel filed called Wind_Power_Monthly
df_refined.to_excel('Wind_Power_Monthly.xlsx', index=False)

In [10]:
# Grouping by Year and Town
grouped_yearly_means = df_refined.groupby(['Town', 'Year'])[
    ['Avg_Temperature_C', 'Avg_Wind_Speed_m/s', 'Surface_Pressure_kPa', 'Air_Density', 'Wind_Power_Density']
].mean().reset_index()
grouped_yearly_means

,Town,Year,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa,Air_Density,Wind_Power_Density
0,Bungoma,2018,21.725833,3.456667,86.920833,1.026918,25.430061
1,Bungoma,2019,22.235833,3.511667,86.916667,1.025100,26.201422
2,Bungoma,2020,21.561667,3.413333,86.934167,1.027639,23.155314
3,Bungoma,2021,22.116667,3.565833,86.893333,1.025224,26.947414
4,Bungoma,2022,22.383333,3.500833,86.871667,1.024056,24.543102
...,...,...,...,...,...,...,...
415,Wote,2020,21.270000,4.462500,87.844167,1.039426,47.248446
416,Wote,2021,21.370000,4.674167,87.842500,1.039069,54.491419
417,Wote,2022,21.295833,4.710833,87.828333,1.039169,54.841443
418,Wote,2023,21.385000,4.685000,87.879167,1.039448,54.104293
419,Wote,2024,21.908333,4.318333,87.880833,1.037611,43.705970

In [11]:
seven_year_means = df_refined.groupby('Town')[
    ['Avg_Temperature_C', 'Avg_Wind_Speed_m/s', 'Surface_Pressure_kPa', 'Air_Density', 'Wind_Power_Density']
].mean().reset_index()
seven_year_means

,Town,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa,Air_Density,Wind_Power_Density
0,Bungoma,22.165238,3.467619,86.917262,1.025346,24.916028
1,Busia,22.165238,3.467619,86.917262,1.025346,24.916028
2,Eldama Ravine,15.670119,3.578571,77.524643,0.935099,24.986379
3,Eldoret,19.065595,3.930119,82.026071,0.977903,46.993351
4,Embu,20.199286,4.393452,85.881548,1.019920,44.224641
5,Garissa,27.448452,7.155119,98.216190,1.138294,267.155348
6,Hola,27.681786,6.468929,100.214643,1.160570,186.044652
7,Homa Bay,23.608571,3.553214,87.394643,1.025959,23.841283
8,Isiolo,22.765476,5.650952,87.781786,1.033438,98.112884
9,Iten,19.250119,2.729048,81.777381,0.974323,11.859836
10,Kabarnet,19.250119,2.729048,81.777381,0.974323,11.859836
11,Kajiado,20.257024,5.565833,84.555357,1.003975,94.599723
12,Kakamega,19.065595,3.930119,82.026071,0.977903,46.993351
13,Kapenguria,17.259524,4.158571,79.335714,0.951709,47.053115
14,Kapsabet,20.521429,3.334405,83.879762,0.995044,25.619744
15,Karungu,22.113810,3.939643,86.530595,1.020959,33.057182
16,Kathwana,24.717500,4.816429,92.396786,1.080648,69.946507
17,Kendu Bay,23.608571,3.553214,87.394643,1.025959,23.841283
18,Kericho,20.031667,3.602738,83.185119,0.988454,24.470348
19,Kerugoya,20.199286,4.393452,85.881548,1.019920,44.224641
20,Kiambu,18.613095,5.207738,82.236667,0.981940,76.661657
21,Kilifi,26.788095,6.383452,100.837143,1.171227,184.001865
22,Kisii,20.031667,3.602738,83.185119,0.988454,24.470348
23,Kisumu,20.521429,3.334405,83.879762,0.995044,25.619744
24,Kitale,17.259524,4.158571,79.335714,0.951709,47.053115
25,Kitui,23.628929,4.254286,91.929881,1.079140,44.982856
26,Konza,19.863690,5.657262,83.715714,0.995336,99.313043
27,Kwale,25.769762,6.182381,99.150357,1.155579,161.771639
28,Lamu,27.106310,7.223690,101.145000,1.173559,259.638717
29,Lodwar,29.453690,5.731548,94.797381,1.091366,112.843719
30,Machakos,20.889881,4.601786,86.879405,1.029352,51.205174
31,Malindi,26.643929,6.636190,100.292381,1.165464,201.700095
32,Maralal,20.606429,5.294524,84.210714,0.998679,84.550627
33,Marsabit,26.555714,8.079286,94.111667,1.093959,308.644513
34,Meru,17.212143,5.190595,81.308214,0.975532,73.652870
35,Migori,22.113810,3.939643,86.530595,1.020959,33.057182
36,Mombasa,26.964643,6.831310,101.194881,1.174690,229.883074
37,Moyale,25.092500,6.861905,91.917619,1.073719,179.741955
38,Murangâ€™a,16.014048,4.655714,79.202024,0.954201,50.358508
39,Mwatate,21.715000,5.374524,90.414286,1.068254,88.546006
40,Mwingi,23.629881,4.502500,91.288452,1.071604,53.363766
41,Nairobi,19.863690,5.657262,83.715714,0.995336,99.313043
42,Naivasha,15.235595,4.228095,77.142024,0.931890,37.335567
43,Nakuru,15.235595,4.228095,77.142024,0.931890,37.335567
44,Namanga,21.647619,4.245595,86.724167,1.024868,48.156619
45,Nanyuki,17.776667,4.670595,80.675000,0.966056,50.676521
46,Narok,17.917024,5.120952,80.103095,0.958768,69.146795
47,Nyamira,20.031667,3.602738,83.185119,0.988454,24.470348
48,Nyeri,16.014048,4.655714,79.202024,0.954201,50.358508
49,Ol Kalou,15.235595,4.228095,77.142024,0.931890,37.335567
50,Rumuruti,21.747262,4.628571,84.427738,0.997385,59.024292
51,Siaya,23.064524,3.356905,87.501548,1.029098,20.904287
52,Sotik,20.031667,3.602738,83.185119,0.988454,24.470348
53,Sotik Post,17.917024,5.120952,80.103095,0.958768,69.146795
54,Thika,18.613095,5.207738,82.236667,0.981940,76.661657
55,Tsavo,25.155714,5.325000,96.485476,1.126834,101.606899
56,Voi,23.741310,5.365833,95.134643,1.116352,101.881505
57,Wajir,27.695000,7.072619,97.481548,1.128859,219.358825
58,Witu,27.106310,7.223690,101.145000,1.173559,259.638717
59,Wote,21.439524,4.578929,87.854405,1.038963,51.392819

In [12]:
#merging seven yeart means to the kenya coordinate data
town_coords = kenya_coordinate_data[['City', 'latitude', 'longitude']]
town_coords.columns = ['Town', 'Latitude', 'Longitude']

map_data = pd.merge(seven_year_means, town_coords, on='Town', how='left')
map_data

,Town,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa,Air_Density,Wind_Power_Density,Latitude,Longitude
0,Bungoma,22.165238,3.467619,86.917262,1.025346,24.916028,0.5704,34.5600
1,Busia,22.165238,3.467619,86.917262,1.025346,24.916028,0.4586,34.1160
2,Eldama Ravine,15.670119,3.578571,77.524643,0.935099,24.986379,0.0504,35.7200
3,Eldoret,19.065595,3.930119,82.026071,0.977903,46.993351,0.5200,35.2700
4,Embu,20.199286,4.393452,85.881548,1.019920,44.224641,-0.5196,37.4500
5,Garissa,27.448452,7.155119,98.216190,1.138294,267.155348,-0.4396,39.6700
6,Hola,27.681786,6.468929,100.214643,1.160570,186.044652,-1.4993,40.0301
7,Homa Bay,23.608571,3.553214,87.394643,1.025959,23.841283,-0.5273,34.4571
8,Isiolo,22.765476,5.650952,87.781786,1.033438,98.112884,0.3546,37.5822
9,Iten,19.250119,2.729048,81.777381,0.974323,11.859836,0.6703,35.5081
10,Kabarnet,19.250119,2.729048,81.777381,0.974323,11.859836,0.4919,35.7430
11,Kajiado,20.257024,5.565833,84.555357,1.003975,94.599723,-1.8524,36.7768
12,Kakamega,19.065595,3.930119,82.026071,0.977903,46.993351,0.2904,34.7300
13,Kapenguria,17.259524,4.158571,79.335714,0.951709,47.053115,1.2389,35.1119
14,Kapsabet,20.521429,3.334405,83.879762,0.995044,25.619744,0.2039,35.1050
15,Karungu,22.113810,3.939643,86.530595,1.020959,33.057182,-0.8496,34.1500
16,Kathwana,24.717500,4.816429,92.396786,1.080648,69.946507,-0.3314,37.8686
17,Kendu Bay,23.608571,3.553214,87.394643,1.025959,23.841283,-0.3596,34.6400
18,Kericho,20.031667,3.602738,83.185119,0.988454,24.470348,-0.3596,35.2800
19,Kerugoya,20.199286,4.393452,85.881548,1.019920,44.224641,-0.4989,37.2803
20,Kiambu,18.613095,5.207738,82.236667,0.981940,76.661657,-1.1714,36.8356
21,Kilifi,26.788095,6.383452,100.837143,1.171227,184.001865,-3.6096,39.8500
22,Kisii,20.031667,3.602738,83.185119,0.988454,24.470348,-0.6696,34.7600
23,Kisumu,20.521429,3.334405,83.879762,0.995044,25.619744,-0.0900,34.7500
24,Kitale,17.259524,4.158571,79.335714,0.951709,47.053115,1.0305,34.9899
25,Kitui,23.628929,4.254286,91.929881,1.079140,44.982856,-1.3670,38.0106
26,Konza,19.863690,5.657262,83.715714,0.995336,99.313043,-1.7496,37.1200
27,Kwale,25.769762,6.182381,99.150357,1.155579,161.771639,-4.1737,39.4521
28,Lamu,27.106310,7.223690,101.145000,1.173559,259.638717,-2.2620,40.9197
29,Lodwar,29.453690,5.731548,94.797381,1.091366,112.843719,3.1304,35.5700
30,Machakos,20.889881,4.601786,86.879405,1.029352,51.205174,-1.5095,37.2600
31,Malindi,26.643929,6.636190,100.292381,1.165464,201.700095,-3.2100,40.1000
32,Maralal,20.606429,5.294524,84.210714,0.998679,84.550627,1.1105,36.6800
33,Marsabit,26.555714,8.079286,94.111667,1.093959,308.644513,2.3300,37.9800
34,Meru,17.212143,5.190595,81.308214,0.975532,73.652870,0.0600,37.6400
35,Migori,22.113810,3.939643,86.530595,1.020959,33.057182,-1.0634,34.4731
36,Mombasa,26.964643,6.831310,101.194881,1.174690,229.883074,-4.0400,39.6899
37,Moyale,25.092500,6.861905,91.917619,1.073719,179.741955,3.5200,39.0500
38,Murangâ€™a,16.014048,4.655714,79.202024,0.954201,50.358508,-0.7210,37.1526
39,Mwatate,21.715000,5.374524,90.414286,1.068254,88.546006,-3.5050,38.3772
40,Mwingi,23.629881,4.502500,91.288452,1.071604,53.363766,-0.9296,38.0700
41,Nairobi,19.863690,5.657262,83.715714,0.995336,99.313043,-1.2833,36.8167
42,Naivasha,15.235595,4.228095,77.142024,0.931890,37.335567,-0.7096,36.4300
43,Nakuru,15.235595,4.228095,77.142024,0.931890,37.335567,-0.2800,36.0700
44,Namanga,21.647619,4.245595,86.724167,1.024868,48.156619,-2.5396,36.8000
45,Nanyuki,17.776667,4.670595,80.675000,0.966056,50.676521,0.0204,37.0600
46,Narok,17.917024,5.120952,80.103095,0.958768,69.146795,-1.0808,35.8711
47,Nyamira,20.031667,3.602738,83.185119,0.988454,24.470348,-0.5633,34.9358
48,Nyeri,16.014048,4.655714,79.202024,0.954201,50.358508,-0.4170,36.9510
49,Ol Kalou,15.235595,4.228095,77.142024,0.931890,37.335567,-0.2643,36.3788
50,Rumuruti,21.747262,4.628571,84.427738,0.997385,59.024292,0.2725,36.5381
51,Siaya,23.064524,3.356905,87.501548,1.029098,20.904287,0.0607,34.2881
52,Sotik,20.031667,3.602738,83.185119,0.988454,24.470348,-0.6796,35.1200
53,Sotik Post,17.917024,5.120952,80.103095,0.958768,69.146795,-0.7813,35.3416
54,Thika,18.613095,5.207738,82.236667,0.981940,76.661657,-1.0396,37.0900
55,Tsavo,25.155714,5.325000,96.485476,1.126834,101.606899,-2.9828,38.4666
56,Voi,23.741310,5.365833,95.134643,1.116352,101.881505,-3.3696,38.5700
57,Wajir,27.695000,7.072619,97.481548,1.128859,219.358825,1.7504,40.0500
58,Witu,27.106310,7.223690,101.145000,1.173559,259.638717,-2.3796,40.4300
59,Wote,21.439524,4.578929,87.854405,1.038963,51.392819,-1.7808,37.6288

In [18]:
#creating an interactive map
fig = px.scatter_map(
    map_data,
    lat="Latitude",
    lon="Longitude",
    color="Wind_Power_Density",
    size="Wind_Power_Density",
    hover_name="Town",
    color_continuous_scale=[(0, "blue"), (1, "red")],
    size_max=15,
    zoom=5,
    title="Average Wind Power Density by Town (2018â€“2024)",
    height=600
)
fig.update_layout(mapbox_style="carto-positron")

fig.show()

In [24]:
map_data_top_5 = map_data.nlargest(6, 'Wind_Power_Density').reset_index(drop=True)
map_data_top_5

,Town,Avg_Temperature_C,Avg_Wind_Speed_m/s,Surface_Pressure_kPa,Air_Density,Wind_Power_Density,Latitude,Longitude
0,Marsabit,26.555714,8.079286,94.111667,1.093959,308.644513,2.3300,37.9800
1,Garissa,27.448452,7.155119,98.216190,1.138294,267.155348,-0.4396,39.6700
2,Lamu,27.106310,7.223690,101.145000,1.173559,259.638717,-2.2620,40.9197
3,Witu,27.106310,7.223690,101.145000,1.173559,259.638717,-2.3796,40.4300
4,Mombasa,26.964643,6.831310,101.194881,1.174690,229.883074,-4.0400,39.6899
5,Wajir,27.695000,7.072619,97.481548,1.128859,219.358825,1.7504,40.0500